function plotAndCompareFromTwoResultFolders(settingsFileName1, settingsFileName2)

input1 = parseFromSettingsFile(settingsFileName1);
input2 = parseFromSettingsFile(settingsFileName2);

plotNeuralControlPersonalizationActivations( ...
    fullfile(input1.ncpResultsDirectory, "synergyWeights.sto"), ...
    fullfile(input1.ncpResultsDirectory, strcat(input1.trialPrefixes{1}, ...
        "_synergyCommands.sto")), ...
    fullfile(input1.mtpResultsDirectory.Text, "muscleActivations", ...
        strcat(input1.trialPrefixes{1}, "_muscleActivations.sto")));
plotNeuralControlPersonalizationActivations( ...
    fullfile(input2.ncpResultsDirectory, "synergyWeights.sto"), ...
    fullfile(input2.ncpResultsDirectory, strcat(input2.trialPrefixes{1}, ...
        "_synergyCommands.sto")), ...
    fullfile(input2.mtpResultsDirectory.Text, "muscleActivations", ...
        strcat(input2.trialPrefixes{1}, "_muscleActivations.sto")));

plotMomentMatchingResults(...
    fullfile(input1.inputDataDirectory, "IDData", strcat(input1.trialPrefixes{1}, ".sto")), ...
    fullfile(input1.ncpResultsDirectory, "modelMoments", ...
        strcat(input1.trialPrefixes{1}, "_modeledMomentsNcp.sto")))
plotMomentMatchingResults(...
    fullfile(input2.inputDataDirectory, "IDData", strcat(input2.trialPrefixes{1}, ".sto")), ...
    fullfile(input2.ncpResultsDirectory, "modelMoments", ...
        strcat(input2.trialPrefixes{1}, "_modeledMomentsNcp.sto")))

reorderAndPlotSynergyControls( ...
    fullfile(input1.ncpResultsDirectory, strcat(input1.trialPrefixes{1}, "_synergyCommands.sto")), ...
    fullfile(input1.ncpResultsDirectory, "synergyWeights.sto"), [], [], ...
    input1.osimxFileName, input1.inputModelFileName, input1.synergy_vector_normalization_method, ...
    input1.synergy_vector_normalization_value, input1.allow_negative_synergy_vector_weights, ...
    fullfile(input2.ncpResultsDirectory, strcat(input2.trialPrefixes{1}, "_synergyCommands.sto")), ...
    fullfile(input2.ncpResultsDirectory, "synergyWeights.sto"), [], [], ...
    input2.osimxFileName, input2.inputModelFileName, input2.synergy_vector_normalization_method, ...
    input2.synergy_vector_normalization_value, input2.allow_negative_synergy_vector_weights)
end


function input = parseFromSettingsFile(settingsFileName)
settingsTree = xml2struct(settingsFileName);
input.ncpResultsDirectory = getFieldByName(settingsTree, 'results_directory').Text;
input.mtpResultsDirectory = getFieldByName(settingsTree, 'mtp_results_directory');
input.inputDataDirectory = getFieldByName(settingsTree, 'data_directory').Text;
input.trialPrefixes = findPrefixes(settingsTree, input.inputDataDirectory);
input.inputModelFileName = parseElementTextByName(settingsTree, 'input_model_file');
input.inputOsimxFileName = parseElementTextByName(settingsTree, 'input_osimx_file');

input.allow_negative_synergy_vector_weights = strcmpi(getTextFromField(...
    getFieldByNameOrAlternate(settingsTree, ...
    'allow_negative_synergy_vector_weights', 'false')), 'true');
input.synergy_vector_normalization_method = 'none';
input.synergy_vector_normalization_value = str2double(getTextFromField(...
    getFieldByNameOrAlternate(settingsTree, ...
    'synergy_vector_normalization_value', '1')));

if ~isempty(input.inputOsimxFileName)
    [~, osimxFileName, ~] = fileparts(input.inputOsimxFileName);
    osimxFileName = fullfile(input.ncpResultsDirectory, ...
        strcat(osimxFileName, "_ncp.osimx"));
else
    [~, modelFileName, ~] = fileparts(input.inputModelFileName);
    osimxFileName = fullfile(input.ncpResultsDirectory, ...
        strcat(modelFileName, "_ncp.osimx"));
end
input.osimxFileName = osimxFileName;
end