% This function is part of the NMSM Pipeline, see file for full license.
%
% This function calculates the position and velocities of the spring
% locations and corresponding ground reaction forces and moments if
% contact surfaces are present. This function also calculates inverse
% dynamic moments.
%
% (struct, struct) -> (struct)
% returns body locations, ground reactions, and inverse dynamic moments

% ----------------------------------------------------------------------- %
% The NMSM Pipeline is a toolkit for model personalization and treatment  %
% optimization of neuromusculoskeletal models through OpenSim. See        %
% nmsm.rice.edu and the NOTICE file for more information. The             %
% NMSM Pipeline is developed at Rice University and supported by the US   %
% National Institutes of Health (R01 EB030520).                           %
%                                                                         %
% Copyright (c) 2021 Rice University and the Authors                      %
% Author(s): Marleny Vega, Claire V. Hammond                              %
%                                                                         %
% Licensed under the Apache License, Version 2.0 (the "License");         %
% you may not use this file except in compliance with the License.        %
% You may obtain a copy of the License at                                 %
% http://www.apache.org/licenses/LICENSE-2.0.                             %
%                                                                         %
% Unless required by applicable law or agreed to in writing, software     %
% distributed under the License is distributed on an "AS IS" BASIS,       %
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or         %
% implied. See the License for the specific language governing            %
% permissions and limitations under the License.                          %
% ----------------------------------------------------------------------- %

function modeledValues = calcTorqueBasedModeledValues(values, inputs, ...
    modeledValues)
[springPositions, springVelocities, modeledValues.bodyLocations, ...
    modeledValues.markerPositions, modeledValues.markerVelocities] = ...
    calculateModeledValuesPointKinematics(values, inputs);
[appliedLoads, modeledValues.groundReactionsLab] = setupAppliedLoads(values, inputs, ...
    modeledValues, springPositions, springVelocities);
[modeledValues.inverseDynamicsMoments, modeledValues.angularMomentum, ....
    modeledValues.metabolicCost, massCenterPositons, ...
    modeledValues.bodyOrientations] = ...
    inverseDynamics(values.time, ...
    values.positions, values.velocities, ...
    values.accelerations, inputs.coordinateNames, appliedLoads, ...
    inputs.mexModel, modeledValues.muscleActivations, ...
    inputs.trackedOrientationIndices, ...
    sum(valueOrAlternate(inputs, 'calculateAngularMomentum', false)), ...
    false, sum(valueOrAlternate(inputs, 'calculateBodyOrientation', ...
    false)), inputs.osimVersion);
if sum(valueOrAlternate(inputs, 'calculateMetabolicCost', false))
    modeledValues.metabolicCost = calcBhargavaMetabolicCost( ...
        inputs.mass, modeledValues.muscleActivations, ...
        modeledValues.normalizedFiberLength, ...
        modeledValues.normalizedFiberVelocity, ...
        inputs.maxIsometricForce, inputs.optimalFiberLength, ...
        inputs.vMaxFactor, inputs.pennationAngle);
end
if sum(valueOrAlternate(inputs, 'calculateBrakingImpulse', false))
    modeledValues.brakingImpulse = calcBrakingForce(modeledValues, ...
        values, inputs.contactSurfaces);
end
if sum(valueOrAlternate(inputs, 'calculatePropulsiveImpulse', false))
    modeledValues.propulsiveImpulse = calcPropulsiveForce( ...
        modeledValues, values, inputs.contactSurfaces);
end
modeledValues.massCenterVelocity = (massCenterPositons(2) - ...
    massCenterPositons(1)) / values.time(end);
end

function [appliedLoads, groundReactionsLab] = setupAppliedLoads(values, ...
    inputs, modeledValues, springPositions, springVelocities)
appliedLoads = [];
numCoordinateLoads = inputs.model.getForceSet().getSize() - ...
    inputs.model.getForceSet().getMuscles().getSize() - ...
    (12 * length(inputs.contactSurfaces));
coordinateLoads = zeros(length(values.time), numCoordinateLoads);
appliedLoads = [zeros(length(values.time), ...
    inputs.model.getForceSet().getMuscles().getSize()) ...
    coordinateLoads];
if ~isempty(inputs.contactSurfaces)
    groundReactions = calcFootGroundReactions(springPositions, ...
        springVelocities, inputs, modeledValues.bodyLocations);
    groundReactionsBody = transferGroundReactionMoments( ...
        modeledValues.bodyLocations, groundReactions, inputs);
    groundReactionsLab = calcGroundReactionsLab(groundReactions);
    appliedLoads = [appliedLoads groundReactionsBody];
else
    groundReactionsLab = [];
end
end

function groundReactionsBody = transferGroundReactionMoments( ...
    bodyLocations, groundReactions, params)

groundReactionsBody = [];
for i = 1:length(params.contactSurfaces)
    parentMoment = transferMoments(bodyLocations.midfootSuperior{i}, ...
        bodyLocations.parent{i}, groundReactions.parentMoments{i}, ...
        groundReactions.parentForces{i});
    childMoment = transferMoments(bodyLocations.midfootSuperior{i}, ...
        bodyLocations.child{i}, groundReactions.childMoments{i}, ...
        groundReactions.childForces{i});
    groundReactionsBody = [groundReactionsBody, ...
        groundReactions.parentForces{i}, groundReactions.childForces{i}, ...
        parentMoment, childMoment];
end
end

function groundReactionsInLab = calcGroundReactionsLab(groundReactions)

for i = 1:length(groundReactions.parentForces)
    groundReactionsInLab.forces{i} = ...
        groundReactions.parentForces{i} + groundReactions.childForces{i};
    groundReactionsInLab.moments{i} = ...
        groundReactions.parentMoments{i} + groundReactions.childMoments{i};
end
end

function [springPositions, springVelocities, bodyLocations, ...
    markerPositions, markerVelocities] = ...
    calculateModeledValuesPointKinematics(values, inputs)
persistent pointLocations; 
persistent bodyIndices;
persistent outputIndices;
springPositions = [];
springVelocities = [];
bodyLocations = [];
markerPositions = [];
markerVelocities = [];
if isempty(pointLocations) % Prepare constant point kinematics inputs
    for i = 1 : length(inputs.contactSurfaces)
        % Parent body springs
        outputIndices(end + 1) = size(pointLocations, 1) + 1;
        pointLocations = cat(1, pointLocations, ...
            inputs.contactSurfaces{i}.parentSpringPointsOnBody);
        bodyIndices = cat(2, bodyIndices, ...
            inputs.contactSurfaces{i}.parentBody * ones(1, ...
        size(inputs.contactSurfaces{i}.parentSpringPointsOnBody, 1)));
        % Child body springs
        outputIndices(end + 1) = size(pointLocations, 1) + 1;
        pointLocations = cat(1, pointLocations, ...
            inputs.contactSurfaces{i}.childSpringPointsOnBody);
        bodyIndices = cat(2, bodyIndices, ...
            inputs.contactSurfaces{i}.childBody * ones(1, ...
        size(inputs.contactSurfaces{i}.childSpringPointsOnBody, 1)));
        % Midfoot superior markers
        outputIndices(end + 1) = size(pointLocations, 1) + 1;
        pointLocations = cat(1, pointLocations, ...
            inputs.contactSurfaces{i}.midfootSuperiorPointOnBody);
        bodyIndices = cat(2, bodyIndices, ...
            inputs.contactSurfaces{i}.midfootSuperiorBody);
        % Parent body origin
        outputIndices(end + 1) = size(pointLocations, 1) + 1;
        pointLocations = cat(1, pointLocations, [0 0 0]);
        bodyIndices = cat(2, bodyIndices, ...
            inputs.contactSurfaces{i}.parentBody);
        % Child body origin
        outputIndices(end + 1) = size(pointLocations, 1) + 1;
        pointLocations = cat(1, pointLocations, [0 0 0]);
        bodyIndices = cat(2, bodyIndices, ...
            inputs.contactSurfaces{i}.childBody);
    end
    if isfield(inputs, 'trackedMarkerNames') ...
            && ~isempty(inputs.trackedMarkerNames)
        outputIndices(end + 1) = size(pointLocations, 1) + 1;
        pointLocations = cat(1, pointLocations, ...
            inputs.trackedMarkerLocations);
        bodyIndices = cat(2, bodyIndices, inputs.trackedMarkerBodyIndices);
    end
    outputIndices(end + 1) = size(pointLocations, 1) + 1;
end
% Run point kinematics
[fullPositions, fullVelocities] = pointKinematics(values.time, ...
    values.positions, values.velocities, pointLocations, bodyIndices, ...
    inputs.mexModel, inputs.coordinateNames, inputs.osimVersion);
% Unpack solved point kinematics
count = 1;
for i = 1 : length(inputs.contactSurfaces)
    springPositions.parent{i} = fullPositions(:, :, ...
        outputIndices(count) : outputIndices(count + 1) - 1);
    springVelocities.parent{i} = fullVelocities(:, :, ...
        outputIndices(count) : outputIndices(count + 1) - 1);
    count = count + 1;
    springPositions.child{i} = fullPositions(:, :, ...
        outputIndices(count) : outputIndices(count + 1) - 1);
    springVelocities.child{i} = fullVelocities(:, :, ...
        outputIndices(count) : outputIndices(count + 1) - 1);
    count = count + 1;
    bodyLocations.midfootSuperior{i} = fullPositions(:, :, ...
        outputIndices(count) : outputIndices(count + 1) - 1);
    bodyLocations.midfootSuperior{i}(:, 2) = ...
        inputs.contactSurfaces{i}.restingSpringLength;
    count = count + 1;
    bodyLocations.parent{i} = fullPositions(:, :, ...
        outputIndices(count) : outputIndices(count + 1) - 1);
    count = count + 1;
    bodyLocations.child{i} = fullPositions(:, :, ...
        outputIndices(count) : outputIndices(count + 1) - 1);
    count = count + 1;
end
if isfield(inputs, 'trackedMarkerNames') ...
        && ~isempty(inputs.trackedMarkerNames)
    markerPositions = fullPositions(:, :, ...
        outputIndices(count) : outputIndices(count + 1) - 1);
    markerVelocities = fullVelocities(:, :, ...
        outputIndices(count) : outputIndices(count + 1) - 1);
end
end
