function plotGcpResultsFromSettingsFile(settingsFileName)
import org.opensim.modeling.Storage
settingsTree = xml2struct(settingsFileName);
resultsDirectory = getFieldByName(settingsTree, 'results_directory').Text;
modelFileName = getFieldByName(settingsTree, 'input_model_file').Text;
modelName = split(modelFileName, ["/", "\"]);
modelName = erase(modelName(end), ".osim");
% Foot 1 Kinematics
plotGcpFootKinematicsFromFiles( ...
    fullfile(resultsDirectory, strcat(modelName, ...
        "_Foot_1_experimentalFootKinematics.sto")), ...
    fullfile(resultsDirectory, strcat(modelName, ...             
        "_Foot_1_optimizedFootKinematics.sto")))

% Foot 1 GRF
plotGcpFootKinematicsFromFiles( ...
    fullfile(resultsDirectory, strcat(modelName, ...             
        "_Foot_2_experimentalFootKinematics.sto")), ...
    fullfile(resultsDirectory, strcat(modelName, ...             
        "_Foot_2_optimizedFootKinematics.sto")))

% Foot 2 Kinematics
plotGcpGroundReactionsFromFiles( ...
    fullfile(resultsDirectory, strcat(modelName, ...             
        "_Foot_1_replacedExperimentalGroundReactions.sto")), ...
    fullfile(resultsDirectory, strcat(modelName, ...             
        "_Foot_1_optimizedGroundReactions.sto")))

% Foot 2 GRF
plotGcpGroundReactionsFromFiles( ...
    fullfile(resultsDirectory, strcat(modelName, ...             
        "_Foot_2_replacedExperimentalGroundReactions.sto")), ...
    fullfile(resultsDirectory, strcat(modelName, ...             
        "_Foot_2_optimizedGroundReactions.sto")))

% Spring grid
plotGcpStiffnessCoefficients( ...
    fullfile("..", "JointModelPersonalization", strcat(modelName, ".osim")), ...
    fullfile(resultsDirectory, strcat(modelName, "_gcp.osimx")))
end

