% Incomplete: how to account for multiple trials for controls initial
% values?

function values = ...
    prepareNonNegativeMatrixFactorizationInitialValues(inputs, params)
values = [];
controls = {};
for i = 1:length(inputs.synergyGroups)
    groupMtpActivationsIndices = ismember( ...
        inputs.mtpActivationsColumnNames, ...
        inputs.synergyGroups{1}.muscleNames);
    groupMtpActivations = inputs.mtpActivations(:, ...
        groupMtpActivationsIndices, :);
    [groupWeights, controls{i}] = nnmf(...
        squeeze(groupMtpActivations(1, :, :)), ...
        inputs.synergyGroups{i}.numSynergies);
    
    values = [values; reshape(groupWeights, [], 1); 0.1 * ... 
        ones(length(inputs.synergyGroups{i}.muscleNames) - ...
        sum(groupMtpActivationsIndices), 1)];
end
end

