function saveJointMomentData(mtpInputs, results, resultsSynx, ...
    resultsSynxNoResiduals, resultsDirectory)
writeMtpDataToSto(mtpInputs.coordinateNames, mtpInputs.prefixes, ...
    results.muscleJointMoments, strcat(resultsDirectory, ...
    "\modelJointMomentsNoSynx"), "_modelJointMomentsNoSynx.sto")
writeMtpDataToSto(mtpInputs.coordinateNames, mtpInputs.prefixes, ...
    resultsSynx.muscleJointMoments, strcat(resultsDirectory, ...
    "\modelJointMomentsSynx"), "_modelJointMomentsSynx.sto")
writeMtpDataToSto(mtpInputs.coordinateNames, mtpInputs.prefixes, ...
    resultsSynxNoResiduals.muscleJointMoments, strcat(resultsDirectory, ...
    "\modelJointMomentsSynxNoResiduals"), "_modelJointMomentsSynxNoResiduals.sto")
writeMtpDataToSto(mtpInputs.coordinateNames, mtpInputs.prefixes, ...
    mtpInputs.inverseDynamicsMoments, strcat(resultsDirectory, ...
    "\inverseDynamicsJointMoments"), "_inverseDynamicsJointMoments.sto")
end