% This function is part of the NMSM Pipeline, see file for full license.
%
% This function saves muscle exctiations and activations with and without
% SynX to their appropriate .sto files in a directory specified by
% resultsDirectory.
%
% (struct, struct, struct, string) -> (None)
% Saves muscle activation and excitation data to .sto file.

% ----------------------------------------------------------------------- %
% The NMSM Pipeline is a toolkit for model personalization and treatment  %
% optimization of neuromusculoskeletal models through OpenSim. See        %
% nmsm.rice.edu and the NOTICE file for more information. The             %
% NMSM Pipeline is developed at Rice University and supported by the US   %
% National Institutes of Health (R01 EB030520).                           %
%                                                                         %
% Copyright (c) 2021 Rice University and the Authors                      %
% Author(s): Robert Salati                                                %
%                                                                         %
% Licensed under the Apache License, Version 2.0 (the "License");         %
% you may not use this file except in compliance with the License.        %
% You may obtain a copy of the License at                                 %
% http://www.apache.org/licenses/LICENSE-2.0.                             %
%                                                                         %
% Unless required by applicable law or agreed to in writing, software     %
% distributed under the License is distributed on an "AS IS" BASIS,       %
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or         %
% implied. See the License for the specific language governing            %
% permissions and limitations under the License.                          %
% ----------------------------------------------------------------------- %

function saveMtpActivationAndExcitationData(mtpInputs, resultsStruct, ...
    resultsDirectory)
writeMtpDataToSto(mtpInputs.muscleNames, mtpInputs.trialNames, ...
    resultsStruct.results.muscleExcitations, ...
    resultsStruct.results.time, ...
    fullfile(resultsDirectory, "muscleExcitations"), ...
    "_muscleExcitations.sto")
writeMtpDataToSto(mtpInputs.muscleNames, mtpInputs.trialNames, ...
    resultsStruct.results.muscleActivations, ...
    resultsStruct.results.time, ...
    fullfile(resultsDirectory, "muscleActivations"), ...
    "_muscleActivations.sto")
if isfield(mtpInputs, "synergyExtrapolation")
    writeMtpDataToSto(mtpInputs.muscleNames, mtpInputs.trialNames, ...
        resultsStruct.resultsSynx.muscleExcitations, ...
        resultsStruct.resultsSynx.time, ...
        fullfile(resultsDirectory, "muscleExcitationsSynx"), ...
        "_muscleExcitationsSynx.sto")
    
    writeMtpDataToSto(mtpInputs.muscleNames, mtpInputs.trialNames, ...
        resultsStruct.resultsSynx.muscleActivations, ...
        resultsStruct.resultsSynx.time, ...
        fullfile(resultsDirectory, "muscleActivationsSynx"), ...
        "_muscleActivationsSynx.sto")

    writeMtpDataToSto(mtpInputs.muscleNames, mtpInputs.trialNames, ...
        resultsStruct.resultsSynx.muscleActivations, ...
        resultsStruct.resultsSynx.time, ...
        fullfile(resultsDirectory, "..", "muscleActivations"), ...
        "_muscleActivations.sto")
else
    writeMtpDataToSto(mtpInputs.muscleNames, mtpInputs.trialNames, ...
        resultsStruct.results.muscleActivations, ...
        resultsStruct.results.time, ...
        fullfile(resultsDirectory, "..", "muscleActivations"), ...
        "_muscleActivations.sto")
end
end