function saveActivationAndExcitationData(mtpInputs, results, ...
    resultsSynx, resultsDirectory)
writeMtpDataToSto(mtpInputs.muscleNames, mtpInputs.prefixes, ...
    results.muscleExcitations, strcat(resultsDirectory, ...
    "\muscleExcitations"), "_muscleExcitations.sto")
writeMtpDataToSto(mtpInputs.muscleNames, mtpInputs.prefixes, ...
    resultsSynx.muscleExcitations, strcat(resultsDirectory, ...
    "\muscleExcitationsSynx"), "_muscleExcitationsSynx.sto")
writeMtpDataToSto(mtpInputs.muscleNames, mtpInputs.prefixes, ...
    results.muscleActivations, strcat(resultsDirectory, ...
    "\muscleActivations"), "_muscleActivations.sto")
writeMtpDataToSto(mtpInputs.muscleNames, mtpInputs.prefixes, ...
    resultsSynx.muscleActivations, strcat(resultsDirectory, ...
    "\muscleActivationsSynx"), "_muscleActivationsSynx.sto")
end