function [lowerBounds, upperBounds] = prepareKinematicCalibrationBounds(...
    functions, params)
lowerBounds = valueOrAlternate(params, 'lowerBounds', ...
    zeros(max(size(functions)),1));
upperBounds = valueOrAlternate(params, 'upperBounds', ...
    zeros(max(size(functions)),1));
end