% This function is part of the NMSM Pipeline, see file for full license.
%
% This function renames the cost terms of Muscle Tendon Personalization
% settings files written for version 1.5 or earlier to the names used by
% the current version, including the cost terms of the Muscle Tendon
% Length Initialization section (see mtliBackwardsCompatibility). Files
% for later versions are left unchanged. Renaming is safe to repeat
% because no current name is a legacy name.
%
% (struct) -> (struct)
% returns the xml2struct settings tree with current cost term names

% ----------------------------------------------------------------------- %
% The NMSM Pipeline is a toolkit for model personalization and treatment  %
% optimization of neuromusculoskeletal models through OpenSim. See        %
% nmsm.rice.edu and the NOTICE file for more information. The             %
% NMSM Pipeline is developed at Rice University and supported by the US   %
% National Institutes of Health (R01 EB030520).                           %
%                                                                         %
% Copyright (c) 2021 Rice University and the Authors                      %
% Author(s): Robert Salati                                                %
%                                                                         %
% Licensed under the Apache License, Version 2.0 (the "License");         %
% you may not use this file except in compliance with the License.        %
% You may obtain a copy of the License at                                 %
% http://www.apache.org/licenses/LICENSE-2.0.                             %
%                                                                         %
% Unless required by applicable law or agreed to in writing, software     %
% distributed under the License is distributed on an "AS IS" BASIS,       %
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or         %
% implied. See the License for the specific language governing            %
% permissions and limitations under the License.                          %
% ----------------------------------------------------------------------- %

function settingsTree = mtpBackwardsCompatibility(settingsTree)
settingsTree = mtliBackwardsCompatibility(settingsTree);
if ~isstruct(settingsTree) || ~isfield(settingsTree, "NMSMPipelineDocument")
    return
end
document = settingsTree.NMSMPipelineDocument;
if ~isLegacySettingsFileVersion(document) || ...
        ~isfield(document, "MuscleTendonPersonalizationTool") || ...
        ~isstruct(document.MuscleTendonPersonalizationTool)
    return
end
tool = document.MuscleTendonPersonalizationTool;
if isfield(tool, "MTPTaskList") && isstruct(tool.MTPTaskList) && ...
        isfield(tool.MTPTaskList, "MTPTask")
    tasks = tool.MTPTaskList.MTPTask;
    if iscell(tasks)
        for i = 1 : numel(tasks)
            tasks{i} = renameCostTermSet(tasks{i}, taskCostTermRenames());
        end
    else
        tasks = renameCostTermSet(tasks, taskCostTermRenames());
    end
    tool.MTPTaskList.MTPTask = tasks;
end
if isfield(tool, "MTPSynergyExtrapolation")
    tool.MTPSynergyExtrapolation = renameCostTermSet( ...
        tool.MTPSynergyExtrapolation, synergyExtrapolationCostTermRenames());
end
document.MuscleTendonPersonalizationTool = tool;
settingsTree.NMSMPipelineDocument = document;
end

function renames = taskCostTermRenames()
renames = containers.Map( ...
    {'inverse_dynamics_joint_moment', ...
    'passive_muscle_force', ...
    'muscle_excitation_penalty', ...
    'emg_scale_factor', ...
    'electromechanical_delay', ...
    'activation_time_constant', ...
    'activation_nonlinearity_constant', ...
    'optimal_muscle_fiber_length', ...
    'tendon_slack_length', ...
    'normalized_muscle_fiber_length', ...
    'minimum_normalized_muscle_fiber_length', ...
    'maximum_normalized_muscle_fiber_length', ...
    'grouped_normalized_muscle_fiber_length', ...
    'grouped_emg_scale_factor', ...
    'grouped_electromechanical_delay'}, ...
    {'inverse_dynamics_load_tracking', ...
    'passive_force_minimization', ...
    'muscle_excitation_minimization', ...
    'emg_scale_factor_deviation', ...
    'electromechanical_delay_deviation', ...
    'activation_time_constant_deviation', ...
    'activation_nonlinearity_deviation', ...
    'optimal_fiber_length_deviation', ...
    'tendon_slack_length_deviation', ...
    'normalized_fiber_length_deviation', ...
    'minimum_normalized_fiber_length_deviation', ...
    'maximum_normalized_fiber_length_deviation', ...
    'grouped_normalized_fiber_length_similarity', ...
    'grouped_emg_scale_factor_similarity', ...
    'grouped_electromechanical_delay_similarity'});
end

function renames = synergyExtrapolationCostTermRenames()
renames = containers.Map( ...
    {'measured_inverse_dynamics_joint_moment', ...
    'extrapolated_muscle_activation', ...
    'residual_muscle_activation'}, ...
    {'inverse_dynamics_load_tracking_SynX', ...
    'extrapolated_muscle_activation_minimization', ...
    'residual_muscle_activation_minimization'});
end
