function ncpInputs = updateNcpInitialGuess(ncpInputs, ...
    precalInputs, optimizedInitialGuess)
[values, precalInputs] = ...
    makeMuscleTendonLengthInitializationValuesAsStruct( ...
    optimizedInitialGuess, precalInputs);
if isfield(ncpInputs, 'mtpActivationsColumnNames')
    nonMtpEntries = ~ismember(ncpInputs.muscleTendonColumnNames, ...
        ncpInputs.mtpActivationsColumnNames);
else
    nonMtpEntries = ones(1, length(ncpInputs.muscleTendonColumnNames));
    nonMtpEntries = xor(nonMtpEntries, 0);
end
if precalInputs.useAbsoluteLengths
    ncpInputs.optimalFiberLength(nonMtpEntries) = ...
        precalInputs.optimalFiberLength(nonMtpEntries);
    ncpInputs.tendonSlackLength(nonMtpEntries) = ...
        precalInputs.tendonSlackLength(nonMtpEntries);
else
    ncpInputs.optimalFiberLength(nonMtpEntries) = ...
        precalInputs.optimalFiberLength(nonMtpEntries) ...
        .* values.optimalFiberLengthScaleFactors(nonMtpEntries);
    ncpInputs.tendonSlackLength(nonMtpEntries) = ...
        precalInputs.tendonSlackLength(nonMtpEntries) .* ...
        values.tendonSlackLengthScaleFactors(nonMtpEntries);
end
newMaxIsometricForce = getMaxIsometricForce(precalInputs, values);
ncpInputs.maxIsometricForce(nonMtpEntries) = ...
    newMaxIsometricForce(nonMtpEntries);
end

