% This function is part of the NMSM Pipeline, see file for full license.
%
% This function takes a parsed settings tree (xml2struct) and finds the
% inverse dynamics, inverse kinematics, ground reactions (if applicable),
% muscle activation (if applicable) and muscle analysis (if applicable)
% data directories.
%
% (struct, struct) -> (struct)
% Returns input structure with experimental data

% ----------------------------------------------------------------------- %
% The NMSM Pipeline is a toolkit for model personalization and treatment  %
% optimization of neuromusculoskeletal models through OpenSim. See        %
% nmsm.rice.edu and the NOTICE file for more information. The             %
% NMSM Pipeline is developed at Rice University and supported by the US   %
% National Institutes of Health (R01 EB030520).                           %
%                                                                         %
% Copyright (c) 2021 Rice University and the Authors                      %
% Author(s): Marleny Vega, Claire V. Hammond                              %
%                                                                         %
% Licensed under the Apache License, Version 2.0 (the "License");         %
% you may not use this file except in compliance with the License.        %
% You may obtain a copy of the License at                                 %
% http://www.apache.org/licenses/LICENSE-2.0.                             %
%                                                                         %
% Unless required by applicable law or agreed to in writing, software     %
% distributed under the License is distributed on an "AS IS" BASIS,       %
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or         %
% implied. See the License for the specific language governing            %
% permissions and limitations under the License.                          %
% ----------------------------------------------------------------------- %

function inputs = parseTreatmentOptimizationDataDirectory(tree, inputs)
[inputs.trackedDirectory, inputs.initialGuessDirectory] = ...
    findDataDirectory(tree);
inputs.trialName = parseTrialName(tree);
inputs = parseExperimentalData(inputs, inputs.trackedDirectory);
inputs = parseSynergyExperimentalData(tree, inputs);
inputs = parseInitialGuessData(inputs, inputs.initialGuessDirectory);
inputs = parseInitialValues(inputs);
end

function [trackedDirectory, initialGuessDirectory] = ...
    findDataDirectory(tree)
trackedDirectory = parseDataDirectory(tree);
initialGuessDirectory = ...
    parseTextOrAlternate(tree, "initial_guess_directory", "");
if strcmp(initialGuessDirectory, "")
    throw(MException("ParseError:RequiredElement", ...
        strcat("Element <initial_guess_directory> required")))
end
end

function inputs = parseExperimentalData(inputs, dataDirectory)
[inputs.experimentalJointMoments, ...
    inputs.inverseDynamicsMomentLabels] = ...
    parseTrialDataTryDirectories( ...
    fullfile(inputs.initialGuessDirectory, "IDData"), ...
    fullfile(dataDirectory, "IDData"), inputs.trialName, inputs.model, true);
[inputs.experimentalJointAngles, inputs.coordinateNames, ...
    experimentalTime] = parseTrialDataTryDirectories( ...
    fullfile(inputs.initialGuessDirectory, "IKData"), ...
    fullfile(dataDirectory, "IKData"), inputs.trialName, inputs.model, true);
inputs.coordinateNamesStrings = inputs.coordinateNames;
inputs.coordinateNames = cellstr(inputs.coordinateNames);
inputs.statesCoordinateIndices = findStatesCoordinateIndices(inputs);
inputs.experimentalTime = experimentalTime - experimentalTime(1);
inputs.initialTime = inputs.experimentalTime;
if isfield(inputs.osimx, 'groundContact') && ...
        isfield(inputs.osimx.groundContact, 'contactSurface')
    inputs.contactSurfaces = inputs.osimx.groundContact.contactSurface;
    for surfaceIndex = 1:length(inputs.contactSurfaces)
        [inputs.contactSurfaces{surfaceIndex} ...
            .experimentalGroundReactionForces, ...
            inputs.contactSurfaces{surfaceIndex} ...
            .experimentalGroundReactionMoments, ...
            inputs.contactSurfaces{surfaceIndex} ...
            .electricalCenter, ...
            inputs.contactSurfaces{surfaceIndex} ...
            .forcePlates] = parseGroundReactionDataWithoutTime( ...
            inputs, dataDirectory, surfaceIndex);
    end
else
    inputs.contactSurfaces = {};
end
end

function inputs = parseInitialGuessData(inputs, dataDirectory)
try
    [inputs.initialJointMoments, ...
        inputs.initialInverseDynamicsMomentLabels] = ...
        parseTrialData(fullfile(dataDirectory, "IDData"), ...
        inputs.trialName, inputs.model);
catch
    inputs.initialJointMoments = inputs.experimentalJointMoments;
    inputs.initialInverseDynamicsMomentLabels = ...
        inputs.inverseDynamicsMomentLabels;
end
try
    [inputs.initialJointAngles, inputs.initialCoordinateNames, ...
        initialTime] = parseTrialDataTryDirectories( ...
        fullfile(inputs.initialGuessDirectory, "IKData"), ...
        fullfile(dataDirectory, "IKData"), inputs.trialName, inputs.model, ...
        false);
catch
    inputs.initialJointAngles = inputs.experimentalJointAngles;
    inputs.initialCoordinateNames = inputs.coordinateNamesStrings;
    initialTime = inputs.experimentalTime;
end
inputs.initialTime = initialTime - initialTime(1);
if isfield(inputs.osimx, 'groundContact') && ...
        isfield(inputs.osimx.groundContact, 'contactSurface')
    for surfaceIndex = 1:length(inputs.contactSurfaces)
        try
            [inputs.contactSurfaces{surfaceIndex} ...
                .initialGroundReactionForces, ...
                inputs.contactSurfaces{surfaceIndex} ...
                .initialGroundReactionMoments, ...
                inputs.contactSurfaces{surfaceIndex} ...
                .initialElectricalCenter] = parseGroundReactionDataWithoutTime( ...
                inputs, dataDirectory, surfaceIndex);
        catch
            inputs.contactSurfaces{surfaceIndex} ...
                .initialGroundReactionForces = ...
                inputs.contactSurfaces{surfaceIndex} ...
                .experimentalGroundReactionForces;
            inputs.contactSurfaces{surfaceIndex} ...
                .initialGroundReactionMoments = ...
                inputs.contactSurfaces{surfaceIndex} ...
                .experimentalGroundReactionMoments;
            inputs.contactSurfaces{surfaceIndex} ...
                .initialElectricalCenter = ...
                inputs.contactSurfaces{surfaceIndex} ...
                .electricalCenter;
        end
    end
end
end

function inputs = parseSynergyExperimentalData(tree, inputs)
if strcmp(inputs.controllerType, "synergy")
    surrogateModelDataDirectory = getTextFromField( ...
        getFieldByNameOrError(tree, 'surrogate_model_data_directory'));
    [inputs.experimentalMuscleActivations, inputs.muscleLabels] = ...
        parseTrialData(inputs.initialGuessDirectory, ...
        strcat(inputs.trialName, "_combinedActivations"), inputs.model);
    [inputs.synergyWeights, inputs.synergyWeightsLabels] = ...
        parseTrialData(inputs.initialGuessDirectory, ...
        "synergyWeights", inputs.model);
    directory = fullfile(surrogateModelDataDirectory, "MAData", inputs.trialName);
    inputs.surrogateModelMomentArms = parseSelectMomentArms(directory, ...
        inputs.surrogateModelCoordinateNames, inputs.muscleNames);
    [inputs.muscleTendonLengths, inputs.muscleTendonColumnNames] = ...
        parseFileFromDirectories(directory, "_Length.sto", inputs.model);
    inputs.muscleTendonLengths = findSpecificMusclesInData( ...
        inputs.muscleTendonLengths, inputs.muscleTendonColumnNames, ...
        inputs.muscleNames);
    inputs.muscleTendonLengths = reshape(permute(inputs.muscleTendonLengths, ...
        [1 3 2]), [], length(inputs.muscleNames));
    inputs.surrogateModelMomentArms = reshape(permute(inputs.surrogateModelMomentArms, [1 4 2 3]), [], ...
        length(inputs.surrogateModelCoordinateNames), length(inputs.muscleNames));
    [inputs.surrogateModelJointAngles, inputs.surrogateIkCoordinateNames, inputs.surrogateTime] = ...
        parseTrialData(fullfile(surrogateModelDataDirectory, "IKData"), ...
        inputs.trialName, inputs.model);
end
end

function inputs = parseInitialValues(inputs)
try
    [inputs.initialStates, inputs.initialStatesLabels, inputs.initialTime] = ...
        parseTrialData(inputs.initialGuessDirectory, ...
        strcat(inputs.trialName, "_states"), inputs.model);
    [~, ~, indices] = intersect(inputs.statesCoordinateNames, ...
        inputs.initialStatesLabels, 'stable');
    assert(length(indices) == length(inputs.statesCoordinateNames), ...
        "<states_coordinate_list> does not match initial guess.")
    inputs.initialStatesLabels(1 : length(indices)) = ...
        inputs.initialStatesLabels(indices);
    inputs.initialStatesLabels(length(indices) + 1 : ...
        length(indices) * 2) = inputs.initialStatesLabels( ...
        indices + length(indices));
    inputs.initialStates(:, 1 : length(indices)) = ...
        inputs.initialStates(:, indices);
    inputs.initialStates(:, length(indices) + 1 : length(indices) * 2) ...
        = inputs.initialStates(:, indices + length(indices));
catch; end
try
    [inputs.initialAccelerations, inputs.initialAccelerationsLabels] = ...
        parseTrialData(inputs.initialGuessDirectory, ...
        strcat(inputs.trialName, "_accelerations"), inputs.model);
    [inputs.initialAccelerations, inputs.initialAccelerationsLabels] = ...
        reorderInitialValues(inputs.initialAccelerations, ...
        inputs.initialAccelerationsLabels, ...
        inputs.statesCoordinateNames, "<states_coordinate_list> does " + ...
        "not match initial accelerations.");
catch; end
try
    [inputs.initialTorqueControls, inputs.initialTorqueControlsLabels] = ...
        parseTrialData(inputs.initialGuessDirectory, ...
        strcat(inputs.trialName, "_torqueControls"), inputs.model);
    [inputs.initialTorqueControls, inputs.initialTorqueControlsLabels] = ...
        reorderInitialValues(inputs.initialTorqueControls, ...
        inputs.initialTorqueControlsLabels, ...
        inputs.torqueControllerCoordinateNames, "Torque control " + ...
        "coordinate list does not match initial guess.");
catch;end
if strcmp(inputs.controllerType, "synergy")
    [inputs.initialSynergyControls, inputs.initialSynergyControlsLabels] = ...
        parseTrialData(inputs.initialGuessDirectory, ...
        strcat(inputs.trialName, "_synergyCommands"), inputs.model);
end
end

function [orderedData, orderedLabels] = reorderInitialValues(newData, ...
    newLabels, referenceLabels, errorMessage)
[~, ~, indices] = intersect(referenceLabels, newLabels, 'stable');
assert(length(indices) == length(referenceLabels) && ...
    length(indices) == length(newLabels), errorMessage)
orderedLabels = newLabels(indices);
orderedData = newData(:, indices);
end

function [data, labels, time] = parseTrialDataTryDirectories( ...
    initialGuessDirectory, dataDirectory, trialName, model, ...
    tryExperimentalFirst)
if ~strcmp(initialGuessDirectory, "")
    if tryExperimentalFirst
        try
            [data, labels, time] = parseTrialData(...
                dataDirectory, trialName, model);
        catch
            [data, labels, time] = parseTrialData( ...
                initialGuessDirectory, trialName, model);
        end
    else
        try
            [data, labels, time] = parseTrialData(...
                initialGuessDirectory, trialName, model);
        catch
            [data, labels, time] = parseTrialData( ...
                dataDirectory, trialName, model);
        end
    end
else
    [data, labels, time] = parseTrialData(dataDirectory, trialName, model);
end
end

function [forces, moments, ec, plates] = ...
    parseGroundReactionDataWithoutTime(inputs, dataDirectory, surfaceIndex)
import org.opensim.modeling.Storage
[grfData, grfColumnNames, grfTime] = parseTrialDataTryDirectories( ...
    fullfile(inputs.initialGuessDirectory, "GRFData"), ...
    fullfile(dataDirectory, "GRFData"), inputs.trialName, inputs.model, true);
contactSurface = inputs.osimx.groundContact.contactSurface{surfaceIndex};
numForcePlates = verifyForcePlateColumns(contactSurface);

plateForces = NaN(length(grfTime), 3, numForcePlates);
plateMoments = NaN(length(grfTime), 3, numForcePlates);
plateElectricalCenters = NaN(length(grfTime), 3, numForcePlates);
for plate = 1:numForcePlates
    for j = 1:3
        column = 3 * (plate - 1) + j;
        plateForces(:, j, plate) = findGroundReactionColumn(grfData, ...
            grfColumnNames, contactSurface.forceColumns(column), ...
            contactSurface.name);
        plateMoments(:, j, plate) = findGroundReactionColumn(grfData, ...
            grfColumnNames, contactSurface.momentColumns(column), ...
            contactSurface.name);
        plateElectricalCenters(:, j, plate) = findGroundReactionColumn( ...
            grfData, grfColumnNames, ...
            contactSurface.electricalCenterColumns(column), ...
            contactSurface.name);
    end
end

[forces, moments, ec] = mergeForcePlateWrenches(plateForces, ...
    plateMoments, plateElectricalCenters);

plates.electricalCenter = plateElectricalCenters;
[plates.windowStartTimes, plates.windowPlates] = ...
    findForcePlateContactWindows(plateForces, grfTime);
end

% Each of the three column lists must name three columns per force plate,
% and all three must agree on how many plates the surface uses.
function numForcePlates = verifyForcePlateColumns(contactSurface)
columnCounts = [numel(contactSurface.forceColumns), ...
    numel(contactSurface.momentColumns), ...
    numel(contactSurface.electricalCenterColumns)];
elementNames = ["force_columns", "moment_columns", ...
    "electrical_center_columns"];
for i = 1:3
    if columnCounts(i) == 0 || mod(columnCounts(i), 3) ~= 0
        throw(MException('', "<" + elementNames(i) + "> for contact " + ...
            "surface " + contactSurface.name + " names " + ...
            columnCounts(i) + " columns. It must name three columns " + ...
            "(X, Y, Z) for each force plate applied to the surface."))
    end
end
if numel(unique(columnCounts)) ~= 1
    throw(MException('', "Contact surface " + contactSurface.name + ...
        " names " + columnCounts(1) + " force, " + columnCounts(2) + ...
        " moment and " + columnCounts(3) + " electrical center " + ...
        "columns. All three must cover the same force plates."))
end
numForcePlates = columnCounts(1) / 3;
end

function column = findGroundReactionColumn(grfData, grfColumnNames, ...
    label, surfaceName)
index = find(strcmpi(grfColumnNames, label), 1);
if isempty(index)
    throw(MException('', "Unable to parse GRF file, column " + label + ...
        " of contact surface " + surfaceName + " is not present."))
end
column = grfData(:, index);
end

% Records which force plate carries the surface at each instant, as the
% normalized time each window starts and the plate active in it. Used only
% to label per-plate result columns, never in the merged wrench.
function [windowStartTimes, windowPlates] = ...
    findForcePlateContactWindows(plateForces, grfTime)
if size(plateForces, 3) == 1
    windowStartTimes = 0;
    windowPlates = 1;
    return
end
[~, activePlate] = max(abs(plateForces(:, 2, :)), [], 3);
activePlate = absorbShortContactRuns(activePlate, 3);
normalizedTime = (grfTime(:) - grfTime(1)) / (grfTime(end) - grfTime(1));
windowIndices = [1; find(diff(activePlate) ~= 0) + 1];
windowStartTimes = normalizedTime(windowIndices)';
windowStartTimes(1) = 0;
windowPlates = activePlate(windowIndices)';
end

% While every plate is unloaded the largest vertical force is baseline
% noise, so the active plate can flap back and forth. Absorbing short runs
% into the preceding one keeps the contact windows contiguous; the boundary
% placed inside an unloaded stretch does not matter because the forces there
% are zero.
function activePlate = absorbShortContactRuns(activePlate, minimumRunLength)
runStartIndices = [1; find(diff(activePlate) ~= 0) + 1; ...
    length(activePlate) + 1];
for i = 1 : length(runStartIndices) - 1
    runStart = runStartIndices(i);
    runEnd = runStartIndices(i + 1) - 1;
    if runStart > 1 && runEnd - runStart + 1 < minimumRunLength
        activePlate(runStart:runEnd) = activePlate(runStart - 1);
    end
end
end

function statesCoordinateIndices = findStatesCoordinateIndices(inputs)
statesCoordinateIndices = zeros(size(inputs.statesCoordinateNames));
for i = 1 : length(inputs.statesCoordinateNames)
    statesCoordinateIndices(i) = find( ...
        ismember(inputs.coordinateNames, inputs.statesCoordinateNames(i)));
end
end
