function inputs = reorderPreprocessedDataByMuscleNames(inputs, muscleNames)

[matchedMuscleNames, ~, indexesInParsedMuscleData] = intersect( ...
    muscleNames, inputs.muscleTendonColumnNames, 'stable');
if length(matchedMuscleNames) ~= length(muscleNames)
    missingMuscles = setdiff(muscleNames, matchedMuscleNames);
    throw(MException('', '%s', "The following muscle(s) are required " + ...
        "(by synergy groups or the coordinate list) but were not found " + ...
        "in the muscle tendon length/velocity data: " + ...
        strjoin(missingMuscles, ", ")))
end

inputs.muscleTendonColumnNames = ...
    inputs.muscleTendonColumnNames(indexesInParsedMuscleData);
inputs.muscleTendonLength = inputs.muscleTendonLength(:, ...
    indexesInParsedMuscleData, :);
inputs.muscleTendonVelocity = inputs.muscleTendonVelocity(:, ...
    indexesInParsedMuscleData, :);

[matchedCoordinateNames, ~, indexesInParsedCoordinateData] = intersect( ...
    inputs.coordinateNames, inputs.inverseDynamicsMomentsColumnNames, 'stable');
if length(matchedCoordinateNames) ~= length(inputs.coordinateNames)
    missingCoordinates = setdiff(inputs.coordinateNames, matchedCoordinateNames);
    throw(MException('', '%s', "The following coordinate(s) are required " + ...
        "but were not found in the inverse dynamics moment data: " + ...
        strjoin(missingCoordinates, ", ")))
end
[matchedMomentArmCoordinateNames, ~, indexesInParsedMuscleAnalysisData] = ...
    intersect(inputs.coordinateNames, inputs.momentArmsCoordinateNames, 'stable');
if length(matchedMomentArmCoordinateNames) ~= length(inputs.coordinateNames)
    missingCoordinates = setdiff(inputs.coordinateNames, ...
        matchedMomentArmCoordinateNames);
    throw(MException('', '%s', "The following coordinate(s) are required " + ...
        "but were not found in the moment arm data: " + ...
        strjoin(missingCoordinates, ", ")))
end

inputs.inverseDynamicsMoments = ...
    inputs.inverseDynamicsMoments(:, indexesInParsedCoordinateData, :);
inputs.momentArms = inputs.momentArms(:, indexesInParsedMuscleAnalysisData, ...
    indexesInParsedMuscleData, :);

if (isfield(inputs, "mtpActivationsColumnNames"))
    [matchedActivationNames, ~, indexesInParsedActivationData] = ...
        intersect(muscleNames, inputs.mtpActivationsColumnNames, 'stable');
    if length(matchedActivationNames) ~= length(muscleNames)
        missingMuscles = setdiff(muscleNames, matchedActivationNames);
        throw(MException('', '%s', "The following muscle(s) are required " + ...
            "but were not found in the MTP activation data: " + ...
            strjoin(missingMuscles, ", ")))
    end

    inputs.mtpActivationsColumnNames = ...
        inputs.mtpActivationsColumnNames(indexesInParsedActivationData);
    inputs.mtpActivations = ...
        inputs.mtpActivations(:, indexesInParsedActivationData, :);
end

end

