function inputs = reorderPreprocessedDataByMuscleNames(inputs, muscleNames)
indexesInParsedData = ismember(muscleNames, ...
    inputs.muscleTendonColumnNames);
inputs.muscleTendonLength = inputs.muscleTendonLength(:, ...
    indexesInParsedData, :);
inputs.muscleTendonVelocity = inputs.muscleTendonVelocity(:, ...
    indexesInParsedData, :);
indexesInParsedData = ismember(inputs.coordinateNames, ...
    inputs.inverseDynamicsMomentsColumnNames);
inputs.inverseDynamicsMoments = ...
    inputs.inverseDynamicsMoments(:, indexesInParsedData, :);
end

