function inputs = reorderPreprocessedDataByMuscleNames(inputs, muscleNames)

[~, ~, indexesInParsedMuscleData] = intersect( ...
    muscleNames, inputs.muscleTendonColumnNames, 'stable');

inputs.muscleTendonColumnNames = ...
    inputs.muscleTendonColumnNames(indexesInParsedMuscleData);
inputs.muscleTendonLength = inputs.muscleTendonLength(:, ...
    indexesInParsedMuscleData, :);
inputs.muscleTendonVelocity = inputs.muscleTendonVelocity(:, ...
    indexesInParsedMuscleData, :);

[~, ~, indexesInParsedCoordinateData] = intersect( ...
    inputs.coordinateNames, inputs.inverseDynamicsMomentsColumnNames, 'stable');
[~, ~, indexesInParsedMuscleAnalysisData] = intersect( ...
    inputs.coordinateNames, inputs.momentArmsCoordinateNames, 'stable');

inputs.inverseDynamicsMoments = ...
    inputs.inverseDynamicsMoments(:, indexesInParsedCoordinateData, :);
inputs.momentArms = inputs.momentArms(:, indexesInParsedMuscleAnalysisData, ...
    indexesInParsedMuscleData, :);

if (isfield(inputs, "mtpActivationsColumnNames"))
    [~, ~, indexesInParsedActivationData] = ...
        intersect(muscleNames, inputs.mtpActivationsColumnNames, 'stable');

    inputs.mtpActivationsColumnNames = ...
        inputs.mtpActivationsColumnNames(indexesInParsedActivationData);
    inputs.mtpActivations = ...
        inputs.mtpActivations(:, indexesInParsedActivationData, :);
end

end

