function [activeMuscleForce, passiveMuscleForce, totalMuscleForce] = ...
    calcMuscleForce(normalizedFiberLength, normalizedFiberVelocity, ...
    maxIsometricForce, muscleActivation)

activeMuscleForce = maxIsometricForce .* (muscleActivation .* ...
    activeForceLengthCurve(normalizedFiberLength) .* ...
    forceVelocityCurve(normalizedFiberVelocity));

passiveMuscleForce = maxIsometricForce .* ...
    passiveForceLengthCurve(normalizedFiberVelocity);

totalMuscleForce = activeMuscleForce + passiveMuscleForce;

end