% This function is part of the NMSM Pipeline, see file for full license.
%
% This function returns all of the constraint term calculation methods
% Tools use this function for the discrete and continuous constraint
% calculations.
%
% inputs:
% constraintTermType - one of ["path", "terminal"]
% controllerType - one of ["torque", "synergy"]
% toolName - one of ["TrackingOptimization", "TreatmentOptimization", ...
%   "DesignOptimization"]
%
% (string, string) -> (struct of function handles, Array of string)
%

% ----------------------------------------------------------------------- %
% The NMSM Pipeline is a toolkit for model personalization and treatment  %
% optimization of neuromusculoskeletal models through OpenSim. See        %
% nmsm.rice.edu and the NOTICE file for more information. The             %
% NMSM Pipeline is developed at Rice University and supported by the US   %
% National Institutes of Health (R01 EB030520).                           %
%                                                                         %
% Copyright (c) 2021 Rice University and the Authors                      %
% Author(s): Marleny Vega, Claire V. Hammond                              %
%                                                                         %
% Licensed under the Apache License, Version 2.0 (the "License");         %
% you may not use this file except in compliance with the License.        %
% You may obtain a copy of the License at                                 %
% http://www.apache.org/licenses/LICENSE-2.0.                             %
%                                                                         %
% Unless required by applicable law or agreed to in writing, software     %
% distributed under the License is distributed on an "AS IS" BASIS,       %
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or         %
% implied. See the License for the specific language governing            %
% permissions and limitations under the License.                          %
% ----------------------------------------------------------------------- %

function [constraintTermCalculations, allowedTypes] = ...
    generateConstraintTermStruct(constraintTermType, controllerType, ...
    toolName)
allowedTypes = getAllowedTypes(constraintTermType, controllerType, ...
    toolName);
constraintTermCalculations = ...
    getConstraintTermCalculations(constraintTermType);
end

function allowedTypes = getAllowedTypes(constraintTermType, ...
    controllerType, toolName)
allowedTypes = [];
if strcmp(controllerType, "torque")
    switch toolName
        case "TrackingOptimization"
            if strcmp(constraintTermType, "path")
                allowedTypes = [ ...
                    "generalized_coordinate_deviation", ...
                    "generalized_coordinate_value", ...
                    "generalized_speed_deviation", ...
                    "generalized_speed_value", ...
                    "generalized_acceleration_deviation", ...
                    "generalized_acceleration_value", ...
                    "marker_position_deviation", ...
                    "marker_position_value", ...
                    "marker_velocity_deviation", ...
                    "marker_velocity_value", ...
                    "body_orientation_deviation", ...
                    "body_orientation_value", ...
                    "kinetic_consistency", ...
                    "root_segment_residual_load", ...
                    "external_force_deviation", ...
                    "external_force_value", ...
                    "external_moment_deviation", ...
                    "external_moment_value", ...
                    "center_of_pressure_deviation", ...
                    "center_of_pressure_value", ...
                    ];
            end
            if strcmp(constraintTermType, "terminal")
                allowedTypes = [ ...
                    "generalized_coordinate_periodicity", ...
                    "initial_generalized_coordinate_deviation", ...
                    "initial_generalized_coordinate_value", ...
                    "final_generalized_coordinate_deviation", ...
                    "final_generalized_coordinate_value", ...
                    "generalized_speed_periodicity", ...
                    "initial_generalized_speed_deviation", ...
                    "initial_generalized_speed_value", ...
                    "final_generalized_speed_deviation", ...
                    "final_generalized_speed_value", ...
                    "marker_position_periodicity", ...
                    "initial_marker_position_deviation", ...
                    "initial_marker_position_value", ...
                    "final_marker_position_deviation", ...
                    "final_marker_position_value", ...
                    "marker_velocity_periodicity", ...
                    "initial_marker_velocity_deviation", ...
                    "initial_marker_velocity_value", ...
                    "final_marker_velocity_deviation", ...
                    "final_marker_velocity_value", ...
                    "body_orientation_periodicity", ...
                    "initial_body_orientation_deviation", ...
                    "initial_body_orientation_value", ...
                    "final_body_orientation_deviation", ...
                    "final_body_orientation_value", ...
                    "root_segment_residual_load_periodicity", ...
                    "external_force_periodicity", ...
                    "initial_external_force_deviation", ...
                    "initial_external_force_value", ...
                    "final_external_force_deviation", ...
                    "final_external_force_value", ...
                    "external_moment_periodicity", ...
                    "initial_external_moment_deviation", ...
                    "initial_external_moment_value", ...
                    "final_external_moment_deviation", ...
                    "final_external_moment_value", ...
                    ];
            end
        case "VerificationOptimization"
            if strcmp(constraintTermType, "path")
                allowedTypes = [ ...
                    "generalized_coordinate_deviation", ...
                    "generalized_coordinate_value", ...
                    "generalized_speed_deviation", ...
                    "generalized_speed_value", ...
                    "generalized_acceleration_deviation", ...
                    "generalized_acceleration_value", ...
                    "marker_position_deviation", ...
                    "marker_position_value", ...
                    "marker_velocity_deviation", ...
                    "marker_velocity_value", ...
                    "body_orientation_deviation", ...
                    "body_orientation_value", ...
                    "kinetic_consistency", ...
                    "root_segment_residual_load", ...
                    "external_force_deviation", ...
                    "external_force_value", ...
                    "external_moment_deviation", ...
                    "external_moment_value", ...
                    ];
            end
            if strcmp(constraintTermType, "terminal")
                allowedTypes = [ ...
                    "generalized_coordinate_periodicity", ...
                    "initial_generalized_coordinate_deviation", ...
                    "initial_generalized_coordinate_value", ...
                    "final_generalized_coordinate_deviation", ...
                    "final_generalized_coordinate_value", ...
                    "generalized_speed_periodicity", ...
                    "initial_generalized_speed_deviation", ...
                    "initial_generalized_speed_value", ...
                    "final_generalized_speed_deviation", ...
                    "final_generalized_speed_value", ...
                    "marker_position_periodicity", ...
                    "initial_marker_position_deviation", ...
                    "initial_marker_position_value", ...
                    "final_marker_position_deviation", ...
                    "final_marker_position_value", ...
                    "marker_velocity_periodicity", ...
                    "initial_marker_velocity_deviation", ...
                    "initial_marker_velocity_value", ...
                    "final_marker_velocity_deviation", ...
                    "final_marker_velocity_value", ...
                    "body_orientation_periodicity", ...
                    "initial_body_orientation_deviation", ...
                    "initial_body_orientation_value", ...
                    "final_body_orientation_deviation", ...
                    "final_body_orientation_value", ...
                    "root_segment_residual_load_periodicity", ...
                    "external_force_periodicity", ...
                    "initial_external_force_deviation", ...
                    "initial_external_force_value", ...
                    "final_external_force_deviation", ...
                    "final_external_force_value", ...
                    "external_moment_periodicity", ...
                    "initial_external_moment_deviation", ...
                    "initial_external_moment_value", ...
                    "final_external_moment_deviation", ...
                    "final_external_moment_value", ...
                    ];
            end
        case "DesignOptimization"
            if strcmp(constraintTermType, "path")
                allowedTypes = [ ...
                    "generalized_coordinate_deviation", ...
                    "generalized_coordinate_value", ...
                    "generalized_speed_deviation", ...
                    "generalized_speed_value", ...
                    "generalized_acceleration_deviation", ...
                    "generalized_acceleration_value", ...
                    "marker_position_deviation", ...
                    "marker_position_value", ...
                    "marker_velocity_deviation", ...
                    "marker_velocity_value", ...
                    "body_orientation_deviation", ...
                    "body_orientation_value", ...
                    "kinetic_consistency", ...
                    "root_segment_residual_load", ...
                    "external_force_deviation", ...
                    "external_force_value", ...
                    "external_moment_deviation", ...
                    "external_moment_value", ...
                    "center_of_pressure_deviation", ...
                    "center_of_pressure_value", ...
                    "limit_normalized_fiber_length", ...
                    "user_defined"
                    ];
            end
            if strcmp(constraintTermType, "terminal")
                allowedTypes = [ ...
                    "generalized_coordinate_periodicity", ...
                    "initial_generalized_coordinate_deviation", ...
                    "initial_generalized_coordinate_value", ...
                    "final_generalized_coordinate_deviation", ...
                    "final_generalized_coordinate_value", ...
                    "generalized_speed_periodicity", ...
                    "initial_generalized_speed_deviation", ...
                    "initial_generalized_speed_value", ...
                    "final_generalized_speed_deviation", ...
                    "final_generalized_speed_value", ...
                    "marker_position_periodicity", ...
                    "initial_marker_position_deviation", ...
                    "initial_marker_position_value", ...
                    "final_marker_position_deviation", ...
                    "final_marker_position_value", ...
                    "marker_velocity_periodicity", ...
                    "initial_marker_velocity_deviation", ...
                    "initial_marker_velocity_value", ...
                    "final_marker_velocity_deviation", ...
                    "final_marker_velocity_value", ...
                    "body_orientation_periodicity", ...
                    "initial_body_orientation_deviation", ...
                    "initial_body_orientation_value", ...
                    "final_body_orientation_deviation", ...
                    "final_body_orientation_value", ...
                    "root_segment_residual_load_periodicity", ...
                    "external_force_periodicity", ...
                    "initial_external_force_deviation", ...
                    "initial_external_force_value", ...
                    "final_external_force_deviation", ...
                    "final_external_force_value", ...
                    "external_moment_periodicity", ...
                    "initial_external_moment_deviation", ...
                    "initial_external_moment_value", ...
                    "final_external_moment_deviation", ...
                    "final_external_moment_value", ...
                    "user_defined"
                    ];
            end
    end
end
if strcmp(controllerType, "synergy")
    switch toolName
        case "TrackingOptimization"
            if strcmp(constraintTermType, "path")
                allowedTypes = [ ...
                    "generalized_coordinate_deviation", ...
                    "generalized_coordinate_value", ...
                    "generalized_speed_deviation", ...
                    "generalized_speed_value", ...
                    "generalized_acceleration_deviation", ...
                    "generalized_acceleration_value", ...
                    "marker_position_deviation", ...
                    "marker_position_value", ...
                    "marker_velocity_deviation", ...
                    "marker_velocity_value", ...
                    "body_orientation_deviation", ...
                    "body_orientation_value", ...
                    "kinetic_consistency", ...
                    "root_segment_residual_load", ...
                    "external_force_deviation", ...
                    "external_force_value", ...
                    "external_moment_deviation", ...
                    "external_moment_value", ...
                    "center_of_pressure_deviation", ...
                    "center_of_pressure_value", ...
                    ];
            end
            if strcmp(constraintTermType, "terminal")
                allowedTypes = [ ...
                    "generalized_coordinate_periodicity", ...
                    "initial_generalized_coordinate_deviation", ...
                    "initial_generalized_coordinate_value", ...
                    "final_generalized_coordinate_deviation", ...
                    "final_generalized_coordinate_value", ...
                    "generalized_speed_periodicity", ...
                    "initial_generalized_speed_deviation", ...
                    "initial_generalized_speed_value", ...
                    "final_generalized_speed_deviation", ...
                    "final_generalized_speed_value", ...
                    "marker_position_periodicity", ...
                    "initial_marker_position_deviation", ...
                    "initial_marker_position_value", ...
                    "final_marker_position_deviation", ...
                    "final_marker_position_value", ...
                    "marker_velocity_periodicity", ...
                    "initial_marker_velocity_deviation", ...
                    "initial_marker_velocity_value", ...
                    "final_marker_velocity_deviation", ...
                    "final_marker_velocity_value", ...
                    "body_orientation_periodicity", ...
                    "initial_body_orientation_deviation", ...
                    "initial_body_orientation_value", ...
                    "final_body_orientation_deviation", ...
                    "final_body_orientation_value", ...
                    "root_segment_residual_load_periodicity", ...
                    "external_force_periodicity", ...
                    "initial_external_force_deviation", ...
                    "initial_external_force_value", ...
                    "final_external_force_deviation", ...
                    "final_external_force_value", ...
                    "external_moment_periodicity", ...
                    "initial_external_moment_deviation", ...
                    "initial_external_moment_value", ...
                    "final_external_moment_deviation", ...
                    "final_external_moment_value", ...
                    "synergy_vector_sum", ...
                    "synergy_vector_magnitude", ...
                    ];
            end
        case "VerificationOptimization"
            if strcmp(constraintTermType, "path")
                allowedTypes = [ ...
                    "generalized_coordinate_deviation", ...
                    "generalized_coordinate_value", ...
                    "generalized_speed_deviation", ...
                    "generalized_speed_value", ...
                    "generalized_acceleration_deviation", ...
                    "generalized_acceleration_value", ...
                    "marker_position_deviation", ...
                    "marker_position_value", ...
                    "marker_velocity_deviation", ...
                    "marker_velocity_value", ...
                    "body_orientation_deviation", ...
                    "body_orientation_value", ...
                    "kinetic_consistency", ...
                    "root_segment_residual_load", ...
                    "external_force_deviation", ...
                    "external_force_value", ...
                    "external_moment_deviation", ...
                    "external_moment_value", ...
                    ];
            end
            if strcmp(constraintTermType, "terminal")
                allowedTypes = [ ...
                    "generalized_coordinate_periodicity", ...
                    "initial_generalized_coordinate_deviation", ...
                    "initial_generalized_coordinate_value", ...
                    "final_generalized_coordinate_deviation", ...
                    "final_generalized_coordinate_value", ...
                    "generalized_speed_periodicity", ...
                    "initial_generalized_speed_deviation", ...
                    "initial_generalized_speed_value", ...
                    "final_generalized_speed_deviation", ...
                    "final_generalized_speed_value", ...
                    "marker_position_periodicity", ...
                    "initial_marker_position_deviation", ...
                    "initial_marker_position_value", ...
                    "final_marker_position_deviation", ...
                    "final_marker_position_value", ...
                    "marker_velocity_periodicity", ...
                    "initial_marker_velocity_deviation", ...
                    "initial_marker_velocity_value", ...
                    "final_marker_velocity_deviation", ...
                    "final_marker_velocity_value", ...
                    "body_orientation_periodicity", ...
                    "initial_body_orientation_deviation", ...
                    "initial_body_orientation_value", ...
                    "final_body_orientation_deviation", ...
                    "final_body_orientation_value", ...
                    "root_segment_residual_load_periodicity", ...
                    "external_force_periodicity", ...
                    "initial_external_force_deviation", ...
                    "initial_external_force_value", ...
                    "final_external_force_deviation", ...
                    "final_external_force_value", ...
                    "external_moment_periodicity", ...
                    "initial_external_moment_deviation", ...
                    "initial_external_moment_value", ...
                    "final_external_moment_deviation", ...
                    "final_external_moment_value", ...
                    ];
            end
        case "DesignOptimization"
            if strcmp(constraintTermType, "path")
                allowedTypes = [ ...
                    "generalized_coordinate_deviation", ...
                    "generalized_coordinate_value", ...
                    "generalized_speed_deviation", ...
                    "generalized_speed_value", ...
                    "generalized_acceleration_deviation", ...
                    "generalized_acceleration_value", ...
                    "marker_position_deviation", ...
                    "marker_position_value", ...
                    "marker_velocity_deviation", ...
                    "marker_velocity_value", ...
                    "body_orientation_deviation", ...
                    "body_orientation_value", ...
                    "kinetic_consistency", ...
                    "root_segment_residual_load", ...
                    "external_force_deviation", ...
                    "external_force_value", ...
                    "external_moment_deviation", ...
                    "external_moment_value", ...
                    "center_of_pressure_deviation", ...
                    "center_of_pressure_value", ...
                    "limit_muscle_activation", ...
                    "limit_normalized_fiber_length", ...
                    "user_defined"
                    ];
            end
            if strcmp(constraintTermType, "terminal")
                allowedTypes = [ ...
                    "generalized_coordinate_periodicity", ...
                    "initial_generalized_coordinate_deviation", ...
                    "initial_generalized_coordinate_value", ...
                    "final_generalized_coordinate_deviation", ...
                    "final_generalized_coordinate_value", ...
                    "generalized_speed_periodicity", ...
                    "initial_generalized_speed_deviation", ...
                    "initial_generalized_speed_value", ...
                    "final_generalized_speed_deviation", ...
                    "final_generalized_speed_value", ...
                    "marker_position_periodicity", ...
                    "initial_marker_position_deviation", ...
                    "initial_marker_position_value", ...
                    "final_marker_position_deviation", ...
                    "final_marker_position_value", ...
                    "marker_velocity_periodicity", ...
                    "initial_marker_velocity_deviation", ...
                    "initial_marker_velocity_value", ...
                    "final_marker_velocity_deviation", ...
                    "final_marker_velocity_value", ...
                    "body_orientation_periodicity", ...
                    "initial_body_orientation_deviation", ...
                    "initial_body_orientation_value", ...
                    "final_body_orientation_deviation", ...
                    "final_body_orientation_value", ...
                    "root_segment_residual_load_periodicity", ...
                    "external_force_periodicity", ...
                    "initial_external_force_deviation", ...
                    "initial_external_force_value", ...
                    "final_external_force_deviation", ...
                    "final_external_force_value", ...
                    "external_moment_periodicity", ...
                    "initial_external_moment_deviation", ...
                    "initial_external_moment_value", ...
                    "final_external_moment_deviation", ...
                    "final_external_moment_value", ...
                    "synergy_vector_sum", ...
                    "synergy_vector_magnitude", ...
                    "user_defined"
                    ];
            end
    end
end
end

function constraintTermCalculations = getConstraintTermCalculations(constraintTermType)

constraintTermCalculations.root_segment_residual_load = @(values, modeledValues, auxdata, constraintTerm) ...
    calcRootSegmentResidualsPathConstraints( ...
    constraintTerm, ...
    constraintTerm.load, ...
    auxdata.inverseDynamicsMomentLabels, ...
    modeledValues.inverseDynamicsMoments, ...
    values.time ...
    );

constraintTermCalculations.kinetic_consistency = @(values, modeledValues, auxdata, constraintTerm) ...
    calcKineticPathConstraint( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues, ...
    values.torqueControls, ...
    constraintTerm.load ...
    );

constraintTermCalculations.limit_muscle_activation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcMuscleActivationsPathConstraint( ...
    auxdata, ...
    modeledValues, ...
    constraintTerm.muscle, ...
    constraintTerm ...
    );

constraintTermCalculations.limit_normalized_fiber_length = @(values, modeledValues, auxdata, constraintTerm) ...
    calcNormalizedFiberLengthPathConstraint( ...
    auxdata, ...
    modeledValues, ...
    constraintTerm.muscle, ...
    constraintTerm ...
    );

constraintTermCalculations.marker_position_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcMarkerPositionDeviationPathConstraint( ...
    constraintTerm, ...
    values.time, ...
    modeledValues.markerPositions, ...
    auxdata ...
    );

constraintTermCalculations.marker_position_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcMarkerPositionValuePathConstraint( ...
    constraintTerm, ...
    values.time, ...
    modeledValues.markerPositions, ...
    auxdata ...
    );

constraintTermCalculations.marker_velocity_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcMarkerVelocityDeviationPathConstraint( ...
    constraintTerm, ...
    values.time, ...
    modeledValues.markerVelocities, ...
    auxdata ...
    );

constraintTermCalculations.marker_velocity_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcMarkerVelocityValuePathConstraint( ...
    constraintTerm, ...
    values.time, ...
    modeledValues.markerVelocities, ...
    auxdata ...
    );

constraintTermCalculations.generalized_coordinate_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcGeneralizedCoodinateDeviationPathConstraint( ...
    auxdata, ...
    values.time, ...
    values.positions, ...
    constraintTerm ...
    );

constraintTermCalculations.generalized_coordinate_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcGeneralizedCoodinateValuePathConstraint( ...
    auxdata, ...
    values.positions, ...
    constraintTerm ...
    );

constraintTermCalculations.generalized_speed_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcGeneralizedSpeedDeviationPathConstraint( ...
    auxdata, ...
    values.time, ...
    values.velocities, ...
    constraintTerm ...
    );

constraintTermCalculations.generalized_speed_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcGeneralizedSpeedValuePathConstraint( ...
    auxdata, ...
    values.velocities, ...
    constraintTerm ...
    );

constraintTermCalculations.generalized_acceleration_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcGeneralizedAccelerationDeviationPathConstraint( ...
    contraintTerm, ...
    auxdata, ...
    values.time, ...
    values.accelerations, ...
    constraintTerm.coordinate ...
    );

constraintTermCalculations.generalized_acceleration_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcGeneralizedAccelerationValuePathConstraint( ...
    constraintTerm, ...
    auxdata, ...
    values.accelerations, ...
    constraintTerm.coordinate ...
    );

constraintTermCalculations.external_force_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcExternalForceDeviationPathConstraint( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.groundReactionsLab.forces, ...
    values.time, ...
    constraintTerm.force ...
    );

constraintTermCalculations.external_force_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcExternalForceValuePathConstraint( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.groundReactionsLab.forces, ...
    values.time, ...
    constraintTerm.force ...
    );

constraintTermCalculations.external_moment_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcExternalMomentDeviationPathConstraint( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.groundReactionsLab.moments, ...
    values.time, ...
    constraintTerm.moment ...
    );

constraintTermCalculations.external_moment_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcExternalMomentValuePathConstraint( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.groundReactionsLab.moments, ...
    values.time, ...
    constraintTerm.moment ...
    );

constraintTermCalculations.body_orientation_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcBodyOrientationDeviationPathConstraint( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    modeledValues.bodyOrientations ...
    );

constraintTermCalculations.body_orientation_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcBodyOrientationValuePathConstraint( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    modeledValues.bodyOrientations ...
    );

constraintTermCalculations.center_of_pressure_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcCenterOfPressureDeviationPathConstraint( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    modeledValues ...
    );

constraintTermCalculations.center_of_pressure_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcCenterOfPressureValuePathConstraint( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    modeledValues ...
    );

constraintTermCalculations.generalized_coordinate_periodicity = @(values, modeledValues, auxdata, constraintTerm) ...
    calcStatePositionPeriodicity( ...
    constraintTerm, ...
    values.statePositions, ...
    auxdata.statesCoordinateNames, ...
    constraintTerm.coordinate ...
    );

constraintTermCalculations.generalized_speed_periodicity = @(values, modeledValues, auxdata, constraintTerm) ...
    calcStateVelocityPeriodicity( ...
    constraintTerm, ...
    values.stateVelocities, ...
    auxdata.statesCoordinateNames, ...
    constraintTerm.coordinate ...
    );

constraintTermCalculations.root_segment_residual_load_periodicity = @(values, modeledValues, auxdata, constraintTerm) ...
    calcRootSegmentResidualsPeriodicity(...
    constraintTerm, ...
    modeledValues.inverseDynamicsMoments, ...
    auxdata.inverseDynamicsMomentLabels, ...
    constraintTerm.load ...
    );

constraintTermCalculations.external_force_periodicity = @(values, modeledValues, auxdata, constraintTerm) ...
    calcExternalForcesPeriodicity(...
    modeledValues.groundReactionsLab.forces, ...
    auxdata.contactSurfaces, ...
    constraintTerm.force, ...
    constraintTerm ...
    );

constraintTermCalculations.external_moment_periodicity = @(values, modeledValues, auxdata, constraintTerm) ...
    calcExternalMomentsPeriodicity(...
    modeledValues.groundReactionsLab.moments, ...
    auxdata.contactSurfaces, ...
    constraintTerm.moment, ...
    constraintTerm ...
    );

constraintTermCalculations.initial_generalized_coordinate_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcInitialGeneralizedCoodinateDeviation( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    values.positions ...
    );

constraintTermCalculations.initial_generalized_coordinate_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcInitialGeneralizedCoodinateValue( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    values.positions ...
    );

constraintTermCalculations.initial_generalized_speed_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcInitialGeneralizedSpeedDeviation( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    values.velocities ...
    );

constraintTermCalculations.initial_generalized_speed_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcInitialGeneralizedSpeedValue( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    values.velocities ...
    );

constraintTermCalculations.final_generalized_coordinate_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcFinalGeneralizedCoodinateDeviation( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    values.positions ...
    );

constraintTermCalculations.final_generalized_coordinate_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcFinalGeneralizedCoodinateValue( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    values.positions ...
    );

constraintTermCalculations.final_generalized_speed_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcFinalGeneralizedSpeedDeviation( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    values.velocities ...
    );

constraintTermCalculations.final_generalized_speed_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcFinalGeneralizedSpeedValue( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    values.velocities ...
    );

constraintTermCalculations.initial_marker_position_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcInitialMarkerPositionDeviation( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.markerPositions, ...
    values.time ...
    );

constraintTermCalculations.initial_marker_position_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcInitialMarkerPositionValue( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.markerPositions, ...
    values.time ...
    );

constraintTermCalculations.initial_marker_velocity_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcInitialMarkerVelocityDeviation( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.markerVelocities, ...
    values.time ...
    );

constraintTermCalculations.initial_marker_velocity_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcInitialMarkerVelocityValue( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.markerVelocities, ...
    values.time ...
    );

constraintTermCalculations.final_marker_position_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcFinalMarkerPositionDeviation( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.markerPositions, ...
    values.time ...
    );

constraintTermCalculations.final_marker_position_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcFinalMarkerPositionValue( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.markerPositions, ...
    values.time ...
    );

constraintTermCalculations.final_marker_velocity_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcFinalMarkerVelocityDeviation( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.markerVelocities, ...
    values.time ...
    );

constraintTermCalculations.final_marker_velocity_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcFinalMarkerVelocityValue( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.markerVelocities, ...
    values.time ...
    );

constraintTermCalculations.marker_position_periodicity = @(values, modeledValues, auxdata, constraintTerm) ...
    calcMarkerPositionPeriodicity( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.markerPositions, ...
    values.time ...
    );

constraintTermCalculations.marker_velocity_periodicity = @(values, modeledValues, auxdata, constraintTerm) ...
    calcMarkerVelocityPeriodicity( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.markerVelocities, ...
    values.time ...
    );

constraintTermCalculations.initial_external_force_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcInitialExternalForceDeviation( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.groundReactionsLab.forces, ...
    values.time, ...
    constraintTerm.force ...
    );

constraintTermCalculations.initial_external_force_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcInitialExternalForceValue( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.groundReactionsLab.forces, ...
    values.time, ...
    constraintTerm.force ...
    );

constraintTermCalculations.initial_external_moment_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcInitialExternalMomentDeviation( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.groundReactionsLab.moments, ...
    values.time, ...
    constraintTerm.moment ...
    );

constraintTermCalculations.initial_external_moment_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcInitialExternalMomentValue( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.groundReactionsLab.moments, ...
    values.time, ...
    constraintTerm.moment ...
    );

constraintTermCalculations.final_external_force_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcFinalExternalForceDeviation( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.groundReactionsLab.forces, ...
    values.time, ...
    constraintTerm.force ...
    );

constraintTermCalculations.final_external_force_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcFinalExternalForceValue( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.groundReactionsLab.forces, ...
    values.time, ...
    constraintTerm.force ...
    );

constraintTermCalculations.final_external_moment_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcFinalExternalMomentDeviation( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.groundReactionsLab.moments, ...
    values.time, ...
    constraintTerm.moment ...
    );

constraintTermCalculations.final_external_moment_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcFinalExternalMomentValue( ...
    constraintTerm, ...
    auxdata, ...
    modeledValues.groundReactionsLab.moments, ...
    values.time, ...
    constraintTerm.moment ...
    );

constraintTermCalculations.initial_body_orientation_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcInitialBodyOrientationDeviation( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    modeledValues.bodyOrientations ...
    );

constraintTermCalculations.initial_body_orientation_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcInitialBodyOrientationValue( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    modeledValues.bodyOrientations ...
    );

constraintTermCalculations.final_body_orientation_deviation = @(values, modeledValues, auxdata, constraintTerm) ...
    calcFinalBodyOrientationDeviation( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    modeledValues.bodyOrientations ...
    );

constraintTermCalculations.final_body_orientation_value = @(values, modeledValues, auxdata, constraintTerm) ...
    calcFinalBodyOrientationValue( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    modeledValues.bodyOrientations ...
    );

constraintTermCalculations.body_orientation_periodicity = @(values, modeledValues, auxdata, constraintTerm) ...
    calcBodyOrientationPeriodicity( ...
    constraintTerm, ...
    auxdata, ...
    values.time, ...
    modeledValues.bodyOrientations ...
    );

constraintTermCalculations.synergy_vector_sum = @(values, modeledValues, auxdata, constraintTerm) ...
    calcSynergyWeightsSum(...
    constraintTerm, ...
    values.synergyWeights, ...
    auxdata.synergyGroups, ...
    constraintTerm.synergy_group);

constraintTermCalculations.synergy_vector_magnitude = @(values, modeledValues, auxdata, constraintTerm) ...
    calcSynergyWeightsMagnitude(...
    constraintTerm, ...
    values.synergyWeights, ...
    auxdata.synergyGroups, ...
    constraintTerm.synergy_group);

constraintTermCalculations.user_defined = @(values, modeledValues, auxdata, constraintTerm) ...
    userDefinedFunction(values, ...
    modeledValues, ...
    auxdata, ...
    constraintTerm, ...
    constraintTermType);
end

function output =  ...
    userDefinedFunction(values, modeledValues, auxdata, constraintTerm, constraintTermType)
output = [];
if strcmp(constraintTerm.constraint_term_type, constraintTermType)
    fn = str2func(constraintTerm.function_name);
    output = fn(values, modeledValues, auxdata, constraintTerm);
end
end
