% This function is part of the NMSM Pipeline, see file for full license.
%
% (struct) -> (struct)
% Prepares body angular velocities for cost and constraint terms.

% ----------------------------------------------------------------------- %
% The NMSM Pipeline is a toolkit for model personalization and treatment  %
% optimization of neuromusculoskeletal models through OpenSim. See        %
% nmsm.rice.edu and the NOTICE file for more information. The             %
% NMSM Pipeline is developed at Rice University and supported by the US   %
% National Institutes of Health (R01 EB030520).                           %
%                                                                         %
% Copyright (c) 2021 Rice University and the Authors                      %
% Author(s): Spencer Williams                                             %
%                                                                         %
% Licensed under the Apache License, Version 2.0 (the "License");         %
% you may not use this file except in compliance with the License.        %
% You may obtain a copy of the License at                                 %
% http://www.apache.org/licenses/LICENSE-2.0.                             %
%                                                                         %
% Unless required by applicable law or agreed to in writing, software     %
% distributed under the License is distributed on an "AS IS" BASIS,       %
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or         %
% implied. See the License for the specific language governing            %
% permissions and limitations under the License.                          %
% ----------------------------------------------------------------------- %

function inputs = makeAngularVelocityTracking(inputs)
names = string([]);
bodies = [];
inputs.calculateBodyAngularVelocity = 0;
angularVelocityCostTerms = [ ...
    "body_angular_velocity_tracking", ...
    "body_angular_velocity_minimization", ...
    ];
angularVelocityConstraintTerms = [ ...
    "body_angular_velocity_deviation", ...
    "body_angular_velocity_value", ...
    "initial_body_angular_velocity_deviation", ...
    "initial_body_angular_velocity_value", ...
    "final_body_angular_velocity_deviation", ...
    "final_body_angular_velocity_value", ...
    "body_angular_velocity_periodicity", ...
    ];
for i = 1:length(inputs.costTerms)
    costTerm = inputs.costTerms{i};
    if costTerm.isEnabled && any(strcmp(costTerm.type, angularVelocityCostTerms))
        names(end + 1) = convertCharsToStrings(inputs.model.getBodySet().get( ...
            costTerm.body).getName().toCharArray()');
        bodies(end + 1) = inputs.model.getBodySet().getIndex( ...
            costTerm.body);
    end
end
for i = 1:length(inputs.path)
    constraintTerm = inputs.path{i};
    if constraintTerm.isEnabled && any(strcmp(constraintTerm.type, angularVelocityConstraintTerms))
        names(end + 1) = convertCharsToStrings(inputs.model.getBodySet().get( ...
            constraintTerm.body).getName().toCharArray()');
        bodies(end + 1) = inputs.model.getBodySet().getIndex( ...
            constraintTerm.body);
    end
end
for i = 1:length(inputs.terminal)
    constraintTerm = inputs.terminal{i};
    if constraintTerm.isEnabled && any(strcmp(constraintTerm.type, angularVelocityConstraintTerms))
        names(end + 1) = convertCharsToStrings(inputs.model.getBodySet().get( ...
            constraintTerm.body).getName().toCharArray()');
        bodies(end + 1) = inputs.model.getBodySet().getIndex( ...
            constraintTerm.body);
    end
end

[inputs.trackedAngularVelocityNames, indices] = unique(names);
inputs.trackedAngularVelocityIndices = bodies(indices);
if ~isempty(inputs.trackedAngularVelocityNames)
    inputs.calculateBodyAngularVelocity = 1;
    appliedLoads = zeros(length(inputs.experimentalTime), ...
        inputs.model.getForceSet.getSize());
    [~, ~, ~, ~, ~, bodyAngularVelocities] = inverseDynamics( ...
        inputs.experimentalTime, inputs.experimentalJointAngles, ...
        inputs.experimentalJointVelocities, ...
        inputs.experimentalJointAccelerations, inputs.coordinateNames, ...
        appliedLoads, inputs.mexModel, [], [], ...
        inputs.trackedAngularVelocityIndices, 0, 0, 0, 1, ...
        inputs.osimVersion);
    inputs.splineBodyAngularVelocitiesLabels = ...
        repelem(inputs.trackedAngularVelocityNames, 1, 3) + ...
        repmat(["_x" "_y" "_z"], 1, ...
        length(inputs.trackedAngularVelocityNames));
    inputs.splineBodyAngularVelocities = makeGcvSplineSet( ...
        inputs.experimentalTime, bodyAngularVelocities, ...
        inputs.splineBodyAngularVelocitiesLabels);
    inputs.experimentalBodyAngularVelocities = bodyAngularVelocities;
end
end
