function cost = calcActivationTrackingCost(modeledValues, ...
    experimentalData, params) % This should be ONLY for those that DO have EMG activations to track.
costWeight = valueOrAlternate(params, ...
    "activationTrackingCostWeight", 1);
errorCenter = valueOrAlternate(params, ...
    "activationErrorCenter", 0);
maximumAllowableError = valueOrAlternate(params, ...
    "activationTrackingMaximumAllowableError", 0.01);
cost = costWeight * calcTrackingCostTerm( ...
    modeledValues.muscleActivations, ...
    experimentalData.muscleActivations, errorCenter, ...
    maximumAllowableError);
end