function cost = calcMomentTrackingCost(modeledValues, ...
    experimentalData, params)
costWeight = valueOrAlternate(params, "momentTrackingCostWeight", 1);
errorCenter = valueOrAlternate(params, "momentTrackingErrorCenter", 0);
maximumAllowableError = valueOrAlternate(params, ...
    "momentTrackingMaximumAllowableError", 2);
cost = costWeight * calcTrackingCostTerm( ...
    modeledValues.muscleJointMoments, ...
    experimentalData.muscleJointMoments, errorCenter, ...
    maximumAllowableError);
end