function cost = calcActivationCost(values, params) % This should be ONLY for those that DO NOT have EMG activations to track.
costWeight = valueOrAlternate(params, ...
    "activationCostWeight", 1);
errorCenter = valueOrAlternate(params, ...
    "activationErrorCenter", 0);
maximumAllowableError = valueOrAlternate(params, ...
    "activationNonlinearityDeviationMaximumAllowableError", 0.05);
cost = costWeight * calcDeviationCostTerm( ...
    values.activations, errorCenter, ...
    maximumAllowableError);
end