mex CXXFLAGS="/$CXXFLAGS -fopenmp" LDFLAGS="/$LDFLAGS -fopenmp"...
    COMPFLAGS="/openmp $COMPFLAGS"...
    inverseDynamicsBasedModeledValuesMexWindows.cpp...
    -L'C:\OpenSim 4.4\sdk\lib'...
    -L'C:\OpenSim 4.4\sdk\Simbody\lib'...
    -L'C:\OpenSim 4.4\sdk\spdlog\lib\spdlog'...
    -L'C:\OpenSim 4.4\sdk\spdlog\include'...
    -L'C:\OpenSim 4.4\sdk\spdlog\include\spdlog'...
    -losimCommon -losimSimulation...
    -losimAnalyses -losimActuators -losimTools...
    -lSimTKcommon -lSimTKmath...
    -lSimTKsimbody -lliblapack...
    -llibblas -losimJavaJNI -losimLepton...
    -lspdlog...
    -I'C:\OpenSim 4.4\sdk\include'...
    -I'C:\OpenSim 4.4\sdk\include\OpenSim'...
    -I'C:\OpenSim 4.4\sdk\Simbody\include'...
    -I'C:\OpenSim 4.4\sdk\include\OpenSim\Simulation'...
    -I'C:\OpenSim 4.4\sdk\spdlog\include'...
    -I'C:\OpenSim 4.4\sdk\spdlog\include\spdlog\details'...
    -I'C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt'...
    -I'C:\OpenSim 4.4\sdk\include\OpenSim\Common'...
    -DWIN32 -D_WINDOWS  -DNDEBUG...
    ; 