mex -v CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS"...
    inverseDynamicsAngularMomentumMexWindows.cpp...  
    -L~/opensim-core/sdk/lib...
    -L~/opensim-core/sdk/Simbody/lib...
    -L~/opensim-core/sdk/spdlog/lib/spdlog...
    -L~/opensim-core/sdk/spdlog/include...
    -L~/opensim-core/sdk/spdlog/include/spdlog...
    -losimCommon -losimSimulation...
    -losimAnalyses -losimActuators -losimTools...
    -lSimTKcommon -lSimTKmath...
    -lSimTKsimbody...
    -losimJavaJNI -losimLepton...
    -lspdlog...
    -I~/opensim-core/sdk/include...
    -I~/opensim-core/sdk/include/OpenSim...
    -I~/opensim-core/sdk/Simbody/include...
    -I~/opensim-core/sdk/Simbody/include/simbody...
    -I~/opensim-core/sdk/include/OpenSim/Simulation...
    -I~/opensim-core/sdk/spdlog/include...
    -DNDEBUG...
    ; 