import org.opensim.modeling.Storage
[~, ~, grfData] = parseMotToComponents(Model(inputs.bodyModel), ...
    Storage("cop_converted_grf.mot"));
centerOfPressure = grfData(16:18, :);
hold on
range = 40:70;
plot(modeledValues.markerPositions.heel(3, range), ...
    modeledValues.markerPositions.heel(1, range), "c-")
plot(modeledValues.markerPositions.toe(3, range), ...
    modeledValues.markerPositions.toe(1, range), "m-")
plot(modeledValues.markerPositions.medial(3, range), ...
    modeledValues.markerPositions.medial(1, range), "y-")
plot(modeledValues.markerPositions.lateral(3, range), ...
    modeledValues.markerPositions.lateral(1, range), "k-")
plot(centerOfPressure(3, range), centerOfPressure(1, range), "r-")
plot(modeledValues.markerPositions.heel(3, range(1)), ...
    modeledValues.markerPositions.heel(1, range(1)), "co")
plot(modeledValues.markerPositions.toe(3, range(1)), ...
    modeledValues.markerPositions.toe(1, range(1)), "mo")
plot(modeledValues.markerPositions.medial(3, range(1)), ...
    modeledValues.markerPositions.medial(1, range(1)), "yo")
plot(modeledValues.markerPositions.lateral(3, range(1)), ...
    modeledValues.markerPositions.lateral(1, range(1)), "ko")
plot(centerOfPressure(3, range(1)), centerOfPressure(1, range(1)), "ro")
hold off