function printJointMomentMatchingError(resultsDirectory)
[jointMomentLabels, muscleJointMoments] = extractSavedData( ...
    resultsDirectory, "modelJointMomentsSynx");
[~, inverseDynamicsMoments] = extractSavedData( ...
    resultsDirectory, "inverseDynamicsJointMoments");
jointMomentsRmse = zeros(size(jointMomentLabels));
jointMomentsMae = zeros(size(jointMomentLabels));
for i = 1 : size(muscleJointMoments, 2)
    jointMomentsRmse(i) = sqrt(sum((muscleJointMoments(:, i) - ...
        inverseDynamicsMoments(:, i)) .^ 2, 'all') / ...
        (numel(inverseDynamicsMoments(:, 1)) - 1));
    jointMomentsMae(i) = sum(abs(muscleJointMoments(:, i) - ...
        inverseDynamicsMoments(:, i)) / ...
        numel(inverseDynamicsMoments(:, 1)), 'all');
end
fprintf(['The root mean sqrt (RMS) errors between model-predicted ' ...
    'and inverse dynamic moments are: \n' ]);
fprintf(['\n ' num2str(jointMomentsRmse) ' \n']);
fprintf(['The mean absolute errors (MAEs) between model-predicted ' ...
    'and inverse dynamic moments are: \n' ]);
fprintf(['\n ' num2str(jointMomentsMae) ' \n']);
end

